name: gcp-workload-identity-federation
description: Grant pipelines access to Google Cloud resources using Workload Identity Federation
author: https://github.com/buildkite-plugins
public: true
requirements:
  - bash
  - buildkite-agent
configuration:
  properties:
    audience:
      type: string
    lifetime:
      type: number
  required:
    - audience
  additionalProperties: false
